import { Metadata } from 'next'

interface CityLayoutProps {
  children: React.ReactNode
  params: {
    state: string
    city: string
  }
}

// Complete city mapping for all cities with providers
const cityMapping: Record<string, {name: string, state: string}> = {
  'albany': { name: 'Albany', state: 'NY' },
  'albuquerque': { name: 'Albuquerque', state: 'NM' },
  'alexandria': { name: 'Alexandria', state: 'VA' },
  'allen': { name: 'Allen', state: 'TX' },
  'allentown': { name: 'Allentown', state: 'PA' },
  'amarillo': { name: 'Amarillo', state: 'TX' },
  'anaheim': { name: 'Anaheim', state: 'CA' },
  'anchorage': { name: 'Anchorage', state: 'AK' },
  'ann-arbor': { name: 'Ann Arbor', state: 'MI' },
  'antioch': { name: 'Antioch', state: 'CA' },
  'arlington': { name: 'Arlington', state: 'TX' },
  'arvada': { name: 'Arvada', state: 'CO' },
  'athens': { name: 'Athens', state: 'GA' },
  'atlanta': { name: 'Atlanta', state: 'GA' },
  'augusta': { name: 'Augusta', state: 'GA' },
  'aurora': { name: 'Aurora', state: 'CO' },
  'austin': { name: 'Austin', state: 'TX' },
  'bakersfield': { name: 'Bakersfield', state: 'CA' },
  'baltimore': { name: 'Baltimore', state: 'MD' },
  'baton-rouge': { name: 'Baton Rouge', state: 'LA' },
  'beaumont': { name: 'Beaumont', state: 'TX' },
  'bellevue': { name: 'Bellevue', state: 'WA' },
  'berkeley': { name: 'Berkeley', state: 'CA' },
  'billings': { name: 'Billings', state: 'MT' },
  'birmingham': { name: 'Birmingham', state: 'AL' },
  'boise': { name: 'Boise', state: 'ID' },
  'boston': { name: 'Boston', state: 'MA' },
  'boulder': { name: 'Boulder', state: 'CO' },
  'bridgeport': { name: 'Bridgeport', state: 'CT' },
  'brownsville': { name: 'Brownsville', state: 'TX' },
  'buffalo': { name: 'Buffalo', state: 'NY' },
  'burbank': { name: 'Burbank', state: 'CA' },
  'cambridge': { name: 'Cambridge', state: 'MA' },
  'cape-coral': { name: 'Cape Coral', state: 'FL' },
  'carrollton': { name: 'Carrollton', state: 'TX' },
  'cary': { name: 'Cary', state: 'NC' },
  'cedar-rapids': { name: 'Cedar Rapids', state: 'IA' },
  'chandler': { name: 'Chandler', state: 'AZ' },
  'charleston': { name: 'Charleston', state: 'SC' },
  'charlotte': { name: 'Charlotte', state: 'NC' },
  'chattanooga': { name: 'Chattanooga', state: 'TN' },
  'chesapeake': { name: 'Chesapeake', state: 'VA' },
  'chicago': { name: 'Chicago', state: 'IL' },
  'chula-vista': { name: 'Chula Vista', state: 'CA' },
  'cincinnati': { name: 'Cincinnati', state: 'OH' },
  'clearwater': { name: 'Clearwater', state: 'FL' },
  'cleveland': { name: 'Cleveland', state: 'OH' },
  'colorado-springs': { name: 'Colorado Springs', state: 'CO' },
  'columbia': { name: 'Columbia', state: 'SC' },
  'columbus': { name: 'Columbus', state: 'OH' },
  'concord': { name: 'Concord', state: 'CA' },
  'coral-springs': { name: 'Coral Springs', state: 'FL' },
  'corona': { name: 'Corona', state: 'CA' },
  'corpus-christi': { name: 'Corpus Christi', state: 'TX' },
  'costa-mesa': { name: 'Costa Mesa', state: 'CA' },
  'dallas': { name: 'Dallas', state: 'TX' },
  'daly-city': { name: 'Daly City', state: 'CA' },
  'dayton': { name: 'Dayton', state: 'OH' },
  'denver': { name: 'Denver', state: 'CO' },
  'des-moines': { name: 'Des Moines', state: 'IA' },
  'detroit': { name: 'Detroit', state: 'MI' },
  'downey': { name: 'Downey', state: 'CA' },
  'durham': { name: 'Durham', state: 'NC' },
  'el-monte': { name: 'El Monte', state: 'CA' },
  'el-paso': { name: 'El Paso', state: 'TX' },
  'elizabeth': { name: 'Elizabeth', state: 'NJ' },
  'elk-grove': { name: 'Elk Grove', state: 'CA' },
  'erie': { name: 'Erie', state: 'PA' },
  'escondido': { name: 'Escondido', state: 'CA' },
  'eugene': { name: 'Eugene', state: 'OR' },
  'evansville': { name: 'Evansville', state: 'IN' },
  'fairfield': { name: 'Fairfield', state: 'CA' },
  'fargo': { name: 'Fargo', state: 'ND' },
  'fayetteville': { name: 'Fayetteville', state: 'NC' },
  'fontana': { name: 'Fontana', state: 'CA' },
  'fort-collins': { name: 'Fort Collins', state: 'CO' },
  'fort-lauderdale': { name: 'Fort Lauderdale', state: 'FL' },
  'fort-wayne': { name: 'Fort Wayne', state: 'IN' },
  'fort-worth': { name: 'Fort Worth', state: 'TX' },
  'fremont': { name: 'Fremont', state: 'CA' },
  'fresno': { name: 'Fresno', state: 'CA' },
  'fullerton': { name: 'Fullerton', state: 'CA' },
  'gainesville': { name: 'Gainesville', state: 'FL' },
  'garden-grove': { name: 'Garden Grove', state: 'CA' },
  'garland': { name: 'Garland', state: 'TX' },
  'gilbert': { name: 'Gilbert', state: 'AZ' },
  'glendale': { name: 'Glendale', state: 'AZ' },
  'grand-prairie': { name: 'Grand Prairie', state: 'TX' },
  'grand-rapids': { name: 'Grand Rapids', state: 'MI' },
  'green-bay': { name: 'Green Bay', state: 'WI' },
  'greensboro': { name: 'Greensboro', state: 'NC' },
  'gresham': { name: 'Gresham', state: 'OR' },
  'hamilton': { name: 'Hamilton', state: 'OH' },
  'hampton': { name: 'Hampton', state: 'VA' },
  'hartford': { name: 'Hartford', state: 'CT' },
  'hayward': { name: 'Hayward', state: 'CA' },
  'henderson': { name: 'Henderson', state: 'NV' },
  'hialeah': { name: 'Hialeah', state: 'FL' },
  'hollywood': { name: 'Hollywood', state: 'FL' },
  'honolulu': { name: 'Honolulu', state: 'HI' },
  'houston': { name: 'Houston', state: 'TX' },
  'huntington-beach': { name: 'Huntington Beach', state: 'CA' },
  'huntsville': { name: 'Huntsville', state: 'AL' },
  'independence': { name: 'Independence', state: 'MO' },
  'indianapolis': { name: 'Indianapolis', state: 'IN' },
  'inglewood': { name: 'Inglewood', state: 'CA' },
  'irvine': { name: 'Irvine', state: 'CA' },
  'irving': { name: 'Irving', state: 'TX' },
  'jackson': { name: 'Jackson', state: 'MS' },
  'jacksonville': { name: 'Jacksonville', state: 'FL' },
  'jersey-city': { name: 'Jersey City', state: 'NJ' },
  'joliet': { name: 'Joliet', state: 'IL' },
  'kansas-city': { name: 'Kansas City', state: 'MO' },
  'kent': { name: 'Kent', state: 'WA' },
  'killeen': { name: 'Killeen', state: 'TX' },
  'knoxville': { name: 'Knoxville', state: 'TN' },
  'lafayette': { name: 'Lafayette', state: 'LA' },
  'lakeland': { name: 'Lakeland', state: 'FL' },
  'lakewood': { name: 'Lakewood', state: 'CO' },
  'lancaster': { name: 'Lancaster', state: 'CA' },
  'lansing': { name: 'Lansing', state: 'MI' },
  'laredo': { name: 'Laredo', state: 'TX' },
  'las-vegas': { name: 'Las Vegas', state: 'NV' },
  'lexington': { name: 'Lexington', state: 'KY' },
  'lincoln': { name: 'Lincoln', state: 'NE' },
  'little-rock': { name: 'Little Rock', state: 'AR' },
  'long-beach': { name: 'Long Beach', state: 'CA' },
  'los-angeles': { name: 'Los Angeles', state: 'CA' },
  'louisville': { name: 'Louisville', state: 'KY' },
  'lowell': { name: 'Lowell', state: 'MA' },
  'lubbock': { name: 'Lubbock', state: 'TX' },
  'madison': { name: 'Madison', state: 'WI' },
  'manchester': { name: 'Manchester', state: 'NH' },
  'mcallen': { name: 'McAllen', state: 'TX' },
  'mckinney': { name: 'McKinney', state: 'TX' },
  'memphis': { name: 'Memphis', state: 'TN' },
  'mesa': { name: 'Mesa', state: 'AZ' },
  'mesquite': { name: 'Mesquite', state: 'TX' },
  'miami': { name: 'Miami', state: 'FL' },
  'milwaukee': { name: 'Milwaukee', state: 'WI' },
  'minneapolis': { name: 'Minneapolis', state: 'MN' },
  'miramar': { name: 'Miramar', state: 'FL' },
  'mobile': { name: 'Mobile', state: 'AL' },
  'modesto': { name: 'Modesto', state: 'CA' },
  'montgomery': { name: 'Montgomery', state: 'AL' },
  'moreno-valley': { name: 'Moreno Valley', state: 'CA' },
  'naperville': { name: 'Naperville', state: 'IL' },
  'nashville': { name: 'Nashville', state: 'TN' },
  'new-haven': { name: 'New Haven', state: 'CT' },
  'new-orleans': { name: 'New Orleans', state: 'LA' },
  'new-york': { name: 'New York', state: 'NY' },
  'newark': { name: 'Newark', state: 'NJ' },
  'newport-news': { name: 'Newport News', state: 'VA' },
  'norfolk': { name: 'Norfolk', state: 'VA' },
  'norman': { name: 'Norman', state: 'OK' },
  'north-las-vegas': { name: 'North Las Vegas', state: 'NV' },
  'norwalk': { name: 'Norwalk', state: 'CA' },
  'oakland': { name: 'Oakland', state: 'CA' },
  'oceanside': { name: 'Oceanside', state: 'CA' },
  'oklahoma-city': { name: 'Oklahoma City', state: 'OK' },
  'olathe': { name: 'Olathe', state: 'KS' },
  'omaha': { name: 'Omaha', state: 'NE' },
  'ontario': { name: 'Ontario', state: 'CA' },
  'orange': { name: 'Orange', state: 'CA' },
  'orlando': { name: 'Orlando', state: 'FL' },
  'overland-park': { name: 'Overland Park', state: 'KS' },
  'oxnard': { name: 'Oxnard', state: 'CA' },
  'palm-bay': { name: 'Palm Bay', state: 'FL' },
  'palmdale': { name: 'Palmdale', state: 'CA' },
  'pasadena': { name: 'Pasadena', state: 'CA' },
  'pasadena-tx': { name: 'Pasadena', state: 'TX' },
  'paterson': { name: 'Paterson', state: 'NJ' },
  'pearland': { name: 'Pearland', state: 'TX' },
  'peoria': { name: 'Peoria', state: 'AZ' },
  'philadelphia': { name: 'Philadelphia', state: 'PA' },
  'phoenix': { name: 'Phoenix', state: 'AZ' },
  'pittsburgh': { name: 'Pittsburgh', state: 'PA' },
  'plano': { name: 'Plano', state: 'TX' },
  'pomona': { name: 'Pomona', state: 'CA' },
  'pompano-beach': { name: 'Pompano Beach', state: 'FL' },
  'port-st-lucie': { name: 'Port St. Lucie', state: 'FL' },
  'portland': { name: 'Portland', state: 'OR' },
  'providence': { name: 'Providence', state: 'RI' },
  'provo': { name: 'Provo', state: 'UT' },
  'pueblo': { name: 'Pueblo', state: 'CO' },
  'raleigh': { name: 'Raleigh', state: 'NC' },
  'rancho-cucamonga': { name: 'Rancho Cucamonga', state: 'CA' },
  'reno': { name: 'Reno', state: 'NV' },
  'richmond': { name: 'Richmond', state: 'VA' },
  'riverside': { name: 'Riverside', state: 'CA' },
  'rochester': { name: 'Rochester', state: 'NY' },
  'rockford': { name: 'Rockford', state: 'IL' },
  'roseville': { name: 'Roseville', state: 'CA' },
  'round-rock': { name: 'Round Rock', state: 'TX' },
  'sacramento': { name: 'Sacramento', state: 'CA' },
  'saint-louis': { name: 'Saint Louis', state: 'MO' },
  'saint-paul': { name: 'Saint Paul', state: 'MN' },
  'saint-petersburg': { name: 'Saint Petersburg', state: 'FL' },
  'salem': { name: 'Salem', state: 'OR' },
  'salinas': { name: 'Salinas', state: 'CA' },
  'salt-lake-city': { name: 'Salt Lake City', state: 'UT' },
  'san-antonio': { name: 'San Antonio', state: 'TX' },
  'san-bernardino': { name: 'San Bernardino', state: 'CA' },
  'san-diego': { name: 'San Diego', state: 'CA' },
  'san-francisco': { name: 'San Francisco', state: 'CA' },
  'san-jose': { name: 'San Jose', state: 'CA' },
  'santa-ana': { name: 'Santa Ana', state: 'CA' },
  'santa-clara': { name: 'Santa Clara', state: 'CA' },
  'santa-clarita': { name: 'Santa Clarita', state: 'CA' },
  'santa-rosa': { name: 'Santa Rosa', state: 'CA' },
  'savannah': { name: 'Savannah', state: 'GA' },
  'scottsdale': { name: 'Scottsdale', state: 'AZ' },
  'seattle': { name: 'Seattle', state: 'WA' },
  'shreveport': { name: 'Shreveport', state: 'LA' },
  'simi-valley': { name: 'Simi Valley', state: 'CA' },
  'sioux-falls': { name: 'Sioux Falls', state: 'SD' },
  'spokane': { name: 'Spokane', state: 'WA' },
  'springfield': { name: 'Springfield', state: 'MO' },
  'st-louis': { name: 'St. Louis', state: 'MO' },
  'st-paul': { name: 'St. Paul', state: 'MN' },
  'st-petersburg': { name: 'St. Petersburg', state: 'FL' },
  'stamford': { name: 'Stamford', state: 'CT' },
  'sterling-heights': { name: 'Sterling Heights', state: 'MI' },
  'stockton': { name: 'Stockton', state: 'CA' },
  'sunnyvale': { name: 'Sunnyvale', state: 'CA' },
  'surprise': { name: 'Surprise', state: 'AZ' },
  'syracuse': { name: 'Syracuse', state: 'NY' },
  'tacoma': { name: 'Tacoma', state: 'WA' },
  'tallahassee': { name: 'Tallahassee', state: 'FL' },
  'tampa': { name: 'Tampa', state: 'FL' },
  'tempe': { name: 'Tempe', state: 'AZ' },
  'thornton': { name: 'Thornton', state: 'CO' },
  'thousand-oaks': { name: 'Thousand Oaks', state: 'CA' },
  'toledo': { name: 'Toledo', state: 'OH' },
  'topeka': { name: 'Topeka', state: 'KS' },
  'torrance': { name: 'Torrance', state: 'CA' },
  'tucson': { name: 'Tucson', state: 'AZ' },
  'tulsa': { name: 'Tulsa', state: 'OK' },
  'vallejo': { name: 'Vallejo', state: 'CA' },
  'vancouver': { name: 'Vancouver', state: 'WA' },
  'ventura': { name: 'Ventura', state: 'CA' },
  'virginia-beach': { name: 'Virginia Beach', state: 'VA' },
  'visalia': { name: 'Visalia', state: 'CA' },
  'waco': { name: 'Waco', state: 'TX' },
  'warren': { name: 'Warren', state: 'MI' },
  'washington': { name: 'Washington', state: 'DC' },
  'waterbury': { name: 'Waterbury', state: 'CT' },
  'west-covina': { name: 'West Covina', state: 'CA' },
  'west-jordan': { name: 'West Jordan', state: 'UT' },
  'west-palm-beach': { name: 'West Palm Beach', state: 'FL' },
  'west-valley-city': { name: 'West Valley City', state: 'UT' },
  'westminster': { name: 'Westminster', state: 'CO' },
  'wichita': { name: 'Wichita', state: 'KS' },
  'wilmington': { name: 'Wilmington', state: 'NC' },
  'winston-salem': { name: 'Winston-Salem', state: 'NC' },
  'worcester': { name: 'Worcester', state: 'MA' },
  'yonkers': { name: 'Yonkers', state: 'NY' }
}

export async function generateMetadata({ params }: { params: { state: string, city: string } }): Promise<Metadata> {
  const cityKey = params.city.toLowerCase().replace(/-/g, '')
  const cityInfo = cityMapping[cityKey]

  if (!cityInfo) {
    return {
      title: 'City Not Found',
      description: 'The requested city was not found.'
    }
  }

  const title = `Mobile Phlebotomy ${cityInfo.name}, ${cityInfo.state} | Expert At-Home Blood Draw (2025)`
  const description = `⭐ Top mobile phlebotomists in ${cityInfo.name}! Licensed professionals come to you. Same-day appointments, insurance billing, HIPAA compliant. Book your at-home blood draw today.`

  return {
    title,
    description,
    keywords: `mobile phlebotomy ${cityInfo.name}, at-home blood draw ${cityInfo.name} ${cityInfo.state}, phlebotomist ${cityInfo.name}, mobile lab ${cityInfo.name}, home blood test ${cityInfo.name}`,
    openGraph: {
      title,
      description,
      type: 'website',
    },
    twitter: {
      title,
      description,
      card: 'summary_large_image',
    },
  }
}

export default function CityLayout({ children }: CityLayoutProps) {
  return children
}