import type { Metadata } from 'next'
import CityPage from '@/app/us/[state]/[city]/page'
import { CITY_LONGFORM } from '@/data/city-longform'

// Generated by scripts/upgrade-city-page.ts — DO NOT EDIT BY HAND.
// Re-run the script to refresh provider counts and specialty data:
//   npx tsx scripts/upgrade-city-page.ts --city=boston --state=massachusetts
//
// This static route takes precedence over the dynamic /us/[state]/[city] route
// for Boston, providing server-side metadata + JSON-LD that the dynamic
// (client) component cannot. The provider list, filters, search, and lead form
// are delegated to the existing dynamic CityPage component below.

const PROVIDER_COUNT = 0
const CITY_NAME = "Boston"
const STATE_ABBR = "MA"
const STATE_NAME = "Massachusetts"
const PRICE_RANGE = "$75–$145"
const CITY_SPECIFIC_COUNT = 0

export const metadata: Metadata = {
  title: "Mobile Phlebotomy Boston, MA: At-Home Blood Draws (2026)",
  description: "Find mobile phlebotomy in Boston, MA. Vetted providers serving the Boston area — Blood Draw, Lab Specimen Collection, Specialty Kit Collections. Typical service fee $75–$145 per visit. Same-day appointments available.",
  keywords: "mobile phlebotomy boston, mobile phlebotomist boston, boston mobile blood draw, at home blood draw boston, mobile lab boston, boston massachusetts phlebotomy, massachusetts mobile phlebotomy",
  alternates: {
    canonical: "https://www.mobilephlebotomy.org/us/massachusetts/boston",
  },
  openGraph: {
    title: "Mobile Phlebotomy Boston, MA: At-Home Blood Draws (2026)",
    description: "Find mobile phlebotomy in Boston, MA. Vetted providers serving the Boston area — Blood Draw, Lab Specimen Collection, Specialty Kit Collections. Typical service fee $75–$145 per visit. Same-day appointments available.",
    url: "https://www.mobilephlebotomy.org/us/massachusetts/boston",
    type: 'website',
  },
}

const localBusinessSchema = {"@context":"https://schema.org","@type":"MedicalBusiness","name":"Mobile Phlebotomy in Boston, MA","description":"Directory of vetted mobile phlebotomists serving Boston, Massachusetts and surrounding areas.","url":"https://www.mobilephlebotomy.org/us/massachusetts/boston","areaServed":{"@type":"City","name":"Boston","containedInPlace":{"@type":"State","name":"Massachusetts"}},"priceRange":"$75–$145","medicalSpecialty":"Phlebotomy"}

const faqSchema = {"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"How much does mobile phlebotomy cost in Boston?","acceptedAnswer":{"@type":"Answer","text":"Mobile phlebotomy in Boston, MA typically costs $75–$145 per visit for the phlebotomist's service fee. Independent providers usually charge less than national services like Quest Mobile ($79) or NPPN ($99). Lab processing fees are billed separately by your lab. Medicare and Medicaid patients in Massachusetts typically pay $0–$25 when the draw is medically necessary and ordered by a physician."}},{"@type":"Question","name":"How fast can I get a mobile phlebotomist in Boston?","acceptedAnswer":{"@type":"Answer","text":"Most Boston-area providers offer same-day or next-day appointments, especially for morning routine draws. STAT (urgent) draws are typically available within 2–4 hours for an added fee. Weekend and evening appointments are available from many independent providers. Confirm availability when you contact the provider."}},{"@type":"Question","name":"Do mobile phlebotomists in Boston accept insurance?","acceptedAnswer":{"@type":"Answer","text":"Many mobile phlebotomists in Boston, MA accept insurance, including Medicare Part B for homebound patients (typical copay $0–$25), state Medicaid programs, and major private insurance plans (often with pre-authorization). Independent providers usually also accept HSA, FSA, and competitive self-pay rates. Confirm insurance acceptance directly with the provider before booking."}},{"@type":"Question","name":"Which labs do Boston mobile phlebotomists work with?","acceptedAnswer":{"@type":"Answer","text":"Most Boston-area mobile phlebotomists routinely drop off specimens at LabCorp and Quest Diagnostics patient service centers. Many also deliver to hospital-affiliated labs and specialty labs when your physician's order specifies a particular lab. Confirm your provider can route to your preferred lab before booking."}}]}

const breadcrumbSchema = {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.mobilephlebotomy.org/"},{"@type":"ListItem","position":2,"name":"United States","item":"https://www.mobilephlebotomy.org/us"},{"@type":"ListItem","position":3,"name":"Massachusetts","item":"https://www.mobilephlebotomy.org/us/massachusetts"},{"@type":"ListItem","position":4,"name":"Boston","item":"https://www.mobilephlebotomy.org/us/massachusetts/boston"}]}

// Long-form local copy ported from legacy P2 metro / P3 city-suffix pages.
const LONGFORM = CITY_LONGFORM["massachusetts/boston"]

export default function BostonMobilePhlebotomyPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      {LONGFORM && (
        <section className="container mx-auto px-4 pt-8 max-w-4xl">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Mobile Phlebotomy in Boston: A Local Guide</h2>
          <div className="prose max-w-none text-gray-700 space-y-4">
            {LONGFORM.paragraphs.map((p, i) => <p key={i}>{p}</p>)}
          </div>
        </section>
      )}
      <CityPage params={{ state: "massachusetts", city: "boston" }} />
    </>
  )
}
