/**
 * Migration: move generated static city pages from /us/{abbr}/{city} to
 * /us/{full-state-name}/{city} to match the site's actual URL convention.
 *
 * The 17 pages bulk-generated earlier (Chicago + 16 metros) landed at paths
 * like /us/fl/miami, /us/il/chicago, /us/ny/new-york. Those URLs 301-redirect
 * to /us/florida/miami, /us/illinois/chicago, /us/new-york/new-york — where
 * the dynamic (client-component) route serves them with no server metadata.
 * Result: every static page I generated is dead code in prod.
 *
 * This script:
 *  1. Reads every app/us/{abbr}/{city}/page.tsx generated by the upgrade script
 *  2. Moves it to app/us/{state-slug}/{city}/page.tsx
 *  3. Rewrites the canonical URL inside each file
 *  4. Cleans up the empty abbreviation directories
 *
 * After this runs, the upgrade-city-page.ts script must also be updated to
 * use the slug path going forward (separate edit).
 */
import * as fs from 'fs'
import * as path from 'path'

// Map from 2-letter abbr → URL slug (full state name, lowercased, hyphenated).
const STATE_SLUGS: Record<string, string> = {
  AL: 'alabama', AK: 'alaska', AZ: 'arizona', AR: 'arkansas', CA: 'california',
  CO: 'colorado', CT: 'connecticut', DE: 'delaware', FL: 'florida', GA: 'georgia',
  HI: 'hawaii', ID: 'idaho', IL: 'illinois', IN: 'indiana', IA: 'iowa',
  KS: 'kansas', KY: 'kentucky', LA: 'louisiana', ME: 'maine', MD: 'maryland',
  MA: 'massachusetts', MI: 'michigan', MN: 'minnesota', MS: 'mississippi',
  MO: 'missouri', MT: 'montana', NE: 'nebraska', NV: 'nevada', NH: 'new-hampshire',
  NJ: 'new-jersey', NM: 'new-mexico', NY: 'new-york', NC: 'north-carolina',
  ND: 'north-dakota', OH: 'ohio', OK: 'oklahoma', OR: 'oregon', PA: 'pennsylvania',
  RI: 'rhode-island', SC: 'south-carolina', SD: 'south-dakota', TN: 'tennessee',
  TX: 'texas', UT: 'utah', VT: 'vermont', VA: 'virginia', WA: 'washington',
  WV: 'west-virginia', WI: 'wisconsin', WY: 'wyoming', DC: 'district-of-columbia',
}

const dryRun = process.argv.includes('--dry-run')
const usRoot = path.join(process.cwd(), 'app', 'us')

function isAbbrDir(name: string): boolean {
  return /^[a-z]{2}$/.test(name) && !!STATE_SLUGS[name.toUpperCase()]
}

async function main() {
  console.log(`=== Fix city page paths (abbr → state slug) ===`)
  console.log(`Mode: ${dryRun ? 'DRY-RUN' : 'LIVE'}\n`)

  const moves: Array<{ from: string; to: string; abbr: string; slug: string; city: string }> = []

  for (const entry of fs.readdirSync(usRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    if (!isAbbrDir(entry.name)) continue

    const abbr = entry.name.toUpperCase()
    const slug = STATE_SLUGS[abbr]
    const abbrDir = path.join(usRoot, entry.name)

    for (const cityEntry of fs.readdirSync(abbrDir, { withFileTypes: true })) {
      if (!cityEntry.isDirectory()) continue
      const cityPagePath = path.join(abbrDir, cityEntry.name, 'page.tsx')
      if (!fs.existsSync(cityPagePath)) continue

      const fromRel = path.relative(process.cwd(), cityPagePath)
      const toDir = path.join(usRoot, slug, cityEntry.name)
      const toPath = path.join(toDir, 'page.tsx')
      const toRel = path.relative(process.cwd(), toPath)

      moves.push({
        from: cityPagePath,
        to: toPath,
        abbr,
        slug,
        city: cityEntry.name,
      })
      console.log(`  ${fromRel}\n    → ${toRel}`)
    }
  }

  console.log(`\n${moves.length} file(s) to migrate.\n`)
  if (moves.length === 0) {
    console.log('Nothing to do.')
    return
  }

  if (dryRun) {
    console.log('(Dry-run. Re-run without --dry-run to perform the migration.)')
    return
  }

  for (const m of moves) {
    const content = fs.readFileSync(m.from, 'utf8')

    // Rewrite the canonical URL inside the file: /us/{abbr}/{city} → /us/{slug}/{city}.
    // The 2-letter abbr literal appears in:
    //   - canonical alternate URL
    //   - openGraph.url
    //   - JSON-LD itemListElement[3].item
    //   - JSON-LD breadcrumb state link item
    //   - the CityPage params.state argument
    // We do a targeted regex over `/us/{abbr}/` literal to avoid touching unrelated content.
    const lowerAbbr = m.abbr.toLowerCase()
    const updated = content
      // URL paths
      .replace(new RegExp(`/us/${lowerAbbr}/`, 'g'), `/us/${m.slug}/`)
      .replace(new RegExp(`/us/${lowerAbbr}\\b`, 'g'), `/us/${m.slug}`)
      // CityPage params.state — was the 2-letter abbr, needs to be the slug for routing
      // to match the dynamic /us/[state]/[city] segment, which is now hit by the slug.
      .replace(new RegExp(`params=\\{ state: "${lowerAbbr}",`, 'g'), `params={ state: "${m.slug}",`)

    fs.mkdirSync(path.dirname(m.to), { recursive: true })
    fs.writeFileSync(m.to, updated, 'utf8')

    // Remove the original file and its now-empty parent if applicable.
    fs.unlinkSync(m.from)
    const cityDir = path.dirname(m.from)
    if (fs.readdirSync(cityDir).length === 0) {
      fs.rmdirSync(cityDir)
    }
    const abbrDir = path.dirname(cityDir)
    if (fs.readdirSync(abbrDir).length === 0) {
      fs.rmdirSync(abbrDir)
    }

    console.log(`✓ ${m.city}: ${m.abbr} → ${m.slug}`)
  }

  console.log(`\nDone. ${moves.length} pages migrated.`)
  console.log(`Now update scripts/upgrade-city-page.ts to use slug paths going forward.`)
}

main().catch(e => { console.error(e); process.exit(1) })
